export const GET_STOCKS_RESPONSE = 'GET_STOCKS_RESPONSE';
export const GET_STOCK_RESPONSE = 'GET_STOCK_RESPONSE';
export const ADD_NEW_STOCK_RESPONSE = 'ADD_NEW_STOCK_RESPONSE';
export const UPDATE_EXISTING_STOCK_RESPONSE = 'UPDATE_EXISTING_STOCK_RESPONSE';
export const DELETE_STOCK_RESPONSE = 'DELETE_STOCK_RESPONSE';

export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
